[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool]
[tool.poetry]
authors = ["AwesomeCronk <<>>"]
description = ""
name = "mow"
version = "0.1.0"
[tool.poetry.dependencies]
hikari = "^2.0.0-alpha.105"
python = "^3.8"
[tool.poetry.dev-dependencies]
